### ISSUE TITLE
Postman test all routes

### ISSUE THREAD

**Issue by zcaceres** [WiseFridgeShopper/wise-fridge-shopper#30]
Test all routes with Postman

**Comment by abc516** [comment]
Tested Get /api/speakers

**Comment by abc516** [comment]
Tested Get /api/speakers/:id
Tested Post /api/speakers
Tested Delete /api/speakers
Tested Put /api/speakers

**Comment by abc516** [comment]
Tested Get /api/magnets
Tested Post /api/magnets
Tested Get /api/magnets/:id
Tested get /api/magnets/:id/reviews
Tested put /api/magnets/:id
Tested post /api/magnets/:id/reviews
